### ISSUE TITLE
Anope 2.1.6. Once Anope is running, it crashes 5 minutes later

### ISSUE THREAD

**Issue by Madriix** [anope/anope#408]
Hi

I updated to Anope 2.1.6. Once Anope is running, it crashes 5 minutes later
It was launched twice. The first time, when it crashed, Anope had started normally. The second crash happened with `./anope --support`

Here is the end of the log:

```
Jun 01 13:31:04.065693 2024] Debug: Received :irc.x.com SASL services.x.com 001OH3NVK S PLAIN
[Jun 01 13:31:04.065734 2024] Debug: Sent :00AAAAAAG SASL irc.x.com 001OH3NVK C +
[Jun 01 13:31:04.066119 2024] Debug: Received :irc.x.com SASL services.x.com 001OH3NVK C [redacted]
[Jun 01 13:31:04.066160 2024] Debug: sql_authentication: Checking authentication for Hey
[Jun 01 13:31:04.122202 2024] Debug: sql_authentication: Successful authentication for Hey
[Jun 01 13:31:04.122249 2024] Debug: Extend for nonexistent type NS_SECURE on 0x55d7524d44a8
Erreur de segmentation
irc.com@ns:~/anope2/services/bin$
```

The problem how should I correct it?

**Comment by SadieCat** [comment]
Would it be possible for you to start in gdb and provide a backtrace of it crashing?

**Comment by Madriix** [comment]
@SadieCat I didn't understand what I had to do to show more logs

**Comment by Madriix** [comment]
@SadieCat It's probably because of this:

`	defaults = "ns_secure ns_private hide_email hide_mask memo_signon memo_receive autoop killprotect"`

I will try without ns_secure this afternoon. 

I'm a little lost with everything that needs to be removed manually.

**Comment by Madriix** [comment]
it's been 15 minutes it's been set up, still no crash, looks good

**Comment by Madriix** [comment]
It crashed after 30 minutes, I didn't think to do ./anope --support, I'll do it

**Comment by Madriix** [comment]
Seems to be another problem :
```
[Jun 02 16:16:26.441414 2024] Debug: sql_authentication: Successful authentication for Dream_Dream
[Jun 02 16:16:26.441451 2024] SASL: xx.134 (3xxx5.134) identified to account Dream_Dream using SASL
[Jun 02 16:16:26.441480 2024] Debug: Sent :00AAAAAAG PRIVMSG #!opers! :SASL: 37.xx (37.1xxxx) identified to account Dream_Dream using SASL
[Jun 02 16:16:26.441517 2024] Debug: Sent :00A SVSLOGIN irc.x.com 0015AYQX3 Dream_Dream
[Jun 02 16:16:26.441572 2024] Debug: Sent :00AAAAAAG SASL irc.x.com 0015AYQX3 D S
[Jun 02 16:16:26.441588 2024] Debug: sql_authentication: Successful authentication for GiseleRP
Erreur de segmentation
```

**Comment by SadieCat** [comment]
> @SadieCat I didn't understand what I had to do to show more logs

Run

    gdb /path/to/bin/anope

Then when GDB starts run

    run -nofork

Then when it crashes run runs this and pastebin the output 

    bt full

**Comment by Madriix** [comment]
@SadieCat I did this for 4 crashes this evening:


`./anope -nofork`

It only returns normal logs; nothing unusual appears.

I also tried your commands with gdb, but it doesn't work. As soon as I type "run -nofork" in gdb, nothing happens.

There might still be a mistake in a configuration file.

**Comment by SadieCat** [comment]
Does the latest git revision fix this issue for you?

**Comment by Madriix** [comment]
@SadieCat  I just copied everything from git, the crash still happens

During make, today and also the first day, I saw this:

```
[ 45%] Built target gl_queue.so
[ 45%] Building CXX object modules/CMakeFiles/gl_server.so.dir/global/gl_server.cpp.o
[ 46%] Linking CXX shared module gl_server.so
[ 46%] Built target gl_server.so
[ 46%] Building CXX object modules/CMakeFiles/global.so.dir/global/global.cpp.o
In member function ‘void GlobalCore::ServerGlobal(BotInfo*, Server*, bool, const Anope::string&)’,
    inlined from ‘virtual bool GlobalCore::SendSingle(const Anope::string&, CommandSource*, BotInfo*, Server*)’ at /home/irc/anope2/anope-2.1.6/modules/global/global.cpp:158:22:
/home/irc/anope2/anope-2.1.6/modules/global/global.cpp:24:53: warning: ‘this’ pointer is null [-Wnonnull]
   24 |                 if (server != Me && !server->IsJuped())
      |                                      ~~~~~~~~~~~~~~~^~
In file included from /home/irc/anope2/anope-2.1.6/include/module.h:37,
                 from /home/irc/anope2/anope-2.1.6/modules/global/global.cpp:12:
/home/irc/anope2/anope-2.1.6/include/servers.h: In member function ‘virtual bool GlobalCore::SendSingle(const Anope::string&, CommandSource*, BotInfo*, Server*)’:
/home/irc/anope2/anope-2.1.6/include/servers.h:166:14: note: in a call to non-static member function ‘bool Server::IsJuped() const’
  166 |         bool IsJuped() const;
      |              ^~~~~~~
In member function ‘void GlobalCore::ServerGlobal(BotInfo*, Server*, bool, const Anope::string&)’,
    inlined from ‘virtual bool GlobalCore::SendSingle(const Anope::string&, CommandSource*, BotInfo*, Server*)’ at /home/irc/anope2/anope-2.1.6/modules/global/global.cpp:158:22:
/home/irc/anope2/anope-2.1.6/modules/global/global.cpp:25:39: warning: ‘this’ pointer is null [-Wnonnull]
   25 |                         server->Notice(sender, message);
      |                         ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
/home/irc/anope2/anope-2.1.6/include/servers.h: In member function ‘virtual bool GlobalCore::SendSingle(const Anope::string&, CommandSource*, BotInfo*, Server*)’:
/home/irc/anope2/anope-2.1.6/include/servers.h:177:14: note: in a call to non-static member function ‘void Server::Notice(BotInfo*, const Anope::string&)’
  177 |         void Notice(BotInfo *source, const Anope::string &message);
      |              ^~~~~~
[ 46%] Linking CXX shared module global.so
[ 46%] Built target global.so
[ 46%] Building CXX object modules/CMakeFiles/greet.so.dir/greet.cpp.o
[ 47%] Linking CXX shared module greet.so
[ 47%] Built target greet.so
[ 47%] Building CXX object modules/CMakeFiles/help.so.dir/help.cpp.o
[ 47%] Linking CXX shared module help.so
```

Could there be a connection to the crash?

I'm running Debian 12 with Virtualmin

**Comment by SadieCat** [comment]
Probably not but I fixed it regardless. Its also unlikely to be related to your config though.

Please can you try GDB again and pastebin the full output? I'm not sure what you did wrong because that works for me.

**Comment by Madriix** [comment]
@SadieCat I found the origin of the crash!

For make, it's good—the error at 46% no longer appears.

Regarding the log during the crash, the bug still occurs around this point:
```
[Jun 04 14:09:26.216893 2024] Debug: sql_authentication: Successful authentication for Carly
Segmentation fault
```

I tried to understand why it crashes sometimes and not others, and I found the difference:

1. When someone logs into their account that has already been created for a long time, it doesn't crash.
2. The crash occurs when a new account is created (for example, if you run /ns drop Carly and then have Carly create their account again with /ns identity in sasl). there it crashes.

**Comment by SadieCat** [comment]
What protocol module are you using?

Also please try GDB again.

**Comment by Madriix** [comment]
`module { name = "unrealircd" }`

**Comment by Madriix** [comment]
@SadieCat I recorded the putty session with ./anope -nofork, which email address can I send it to?

I tried again, it still crashes when creating a new account that a user has just made, here anope crashes. What is surprising is that as soon as I restart Anope, the account has been created, so the user can log in without any crashes.

**Comment by SadieCat** [comment]
Recording the session isn't useful. I need GDB output to be able to diagnose this properly.

**Comment by Madriix** [comment]
For about 5 years, every time I update Anope, I almost do a complete new installation with:
1. wget https://github.com/anope/anope/archive/refs/tags/2.1.6.tar.gz
2. ./Config (leaving everything at default except the path which is: /home/irc/anope2/services)
3. ./extras activating mysql.cpp
4. Here I make some modifications in the Anope source files (see the modified files below)
5. cd build
6. make
7. make install (making a backup of the old folder by duplicating it)
8. Then I start Anope with ./anope

Here are the modified cpp files:
https://github.com/anope/anope/blob/2.1/modules/sql_authentication.cpp#L135
Below line 135, I add:
`q.SetValue("d", u->GetIdent());`

And below line 141, I add:
`q.SetValue("d", "");`

In the configuration and the SQL query, I don't make any changes, it remains the same as usual.

In the `third` directory, I add `ns_sagroup.cpp` and `ns_saregister.cpp`.

In `webcpanel`, I rename the file `register.html` to `register_old.html` and duplicate it to provide a link for registering on the site.

I think that's all, I change almost nothing. Maybe I modified something incorrectly, and I should start over.

**Comment by TehPeGaSuS** [comment]
Please provide the requested GDB output.
- Install GDB in your machine if not installed yet
- Go to the anope folder
- Type: `set logging overwrite on`
- Type: `set logging enabled off` followed by `set logging enabled on` (this will make sure that the gdb session file will be started new)
- Type: `gdb ./bin/anope`
- Type: `run --nofork`
- After Anope crashing type `bt full` and hit **Enter** until there's no more outupt
- Type: `exit` and answer **y** it is asks for something like:
```
A debugging session is active.

	Inferior 1 [process 52248] will be killed.

Quit anyway? (y or n)
```
- Now you can either copy the content of the `gdb.txt` file and paste it somewhere or you can just `cat gdb.txt | nc termbin.com 9999` and provide the URL.

**Until you provide such info it's impossible to help you further.**

**Comment by Madriix** [comment]
Thanks for all the GDB tutorial

Indeed it displays errors that I did not see before, vocal the log:

```
[Jun 10 03:36:02 2024] CHANNEL: Wows!o-dcs-fr1944905-1@galaxy-....ipae6991ca.cloud-44db40.irc....com join #...
[Jun 10 03:36:02 2024] CHANNEL: Wows!o-dcs-fr1944905-1@galaxy-....ipae6991ca.cloud-44db40.irc....com join #...

Thread 1 "anope" received signal SIGSEGV, Segmentation fault.
0x00007ffff7164721 in NSCert::OnNickRegister(User*, NickAlias*, Anope::string const&) () from modules/ns_cert.so
(gdb)

```





```
(gdb) bt full
#0  0x00007ffff7164721 in NSCert::OnNickRegister(User*, NickAlias*, Anope::string const&) () from modules/ns_cert.so
No symbol table info available.
#1  0x00007ffff5fa8a40 in SQLAuthenticationResult::OnResult(SQL::Result const&) () from modules/sql_authentication.so
No symbol table info available.
#2  0x00007ffff6dd1332 in ModuleSQL::OnNotify() () from modules/mysql.so
No symbol table info available.
#3  0x00005555556400b5 in Pipe::ProcessRead() ()
No symbol table info available.
#4  0x0000555555669071 in SocketEngine::Process() ()
No symbol table info available.
#5  0x00005555555a6f71 in main ()
No symbol table info available.
(gdb)
```

**Comment by SadieCat** [comment]
I think this should be fixed. Can you test the latest 2.1 git?
